version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
  jobs:
    build:
      - pip install pydoc-markdown==4.5.1
      - pip install jinja2==3.0.3
      - pydoc-markdown --build --site-dir _build/html
      - python -m mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml
