version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  jobs:
    post_install:
      - pip install pydoc-markdown==4.5.1
      - pydoc-markdown --build --site-dir "$PWD/_build/html"
