version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
build:
  os: ubuntu-20.04
  jobs:
    post_install:
      - pip install pydoc-markdown==4.5.1
      - pydoc-markdown --build --site-dir "$PWD/_build/html"
