version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-20.04
  tools:
    python:
      version: "3.10"
      install:
        packages:
          - pydoc-markdown==4.5.1
    post_install:
      - pydoc-markdown --build --site-dir "$PWD/_build/html"
